# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [38]:
print('Numpy Version:', np.__version__)
np.show_config()

Numpy Version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4347739648
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a51i_mbs7m/croot/numpy_and_numpy_base_1708638620867/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdebug-prefix-map=/opt/anac

#### 3. Create a null vector of size 10 (★☆☆)

In [11]:
zero = np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [13]:
array1 = np.array([1,2,3,4,5])
memory_size = array1.nbytes
print("memory size of the array:", memory_size, "bytes")

memory size of the array: 40 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [15]:
zero = np.zeros(10)
zero[4] = 1
print(zero)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [25]:
array = np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [42]:
sort_array_desc = np.sort(array)[::-1]
print("내림차순으로 정렬:\n", sort_array_desc)

내림차순으로 정렬:
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [34]:
array1d = np.arange(start=0, stop=9)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

array2d:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [44]:
array = np.array([1,2,0,0,4,0])
non_zero_indices = array[array > 0]
print(non_zero_indices)

[1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [48]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [50]:
array = np.random.random((3,3,3))
print(array)

[[[0.60654223 0.10693114 0.20164886]
  [0.09937325 0.52638864 0.72165988]
  [0.39726168 0.32533445 0.80038555]]

 [[0.7884383  0.95720606 0.85742224]
  [0.74996001 0.87574347 0.05498751]
  [0.58180374 0.60104143 0.02390323]]

 [[0.27467149 0.19951261 0.52589175]
  [0.20351383 0.33077672 0.00910028]
  [0.91768792 0.05884019 0.30100733]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [54]:
array = np.random.random((10,10))
min_value = np.min(array)
max_value = np.max(array)
print(array)
print("min_value = ", min_value)
print("max_value = ", max_value)

[[0.90623969 0.94797279 0.34874277 0.1482107  0.45247439 0.62915751
  0.15163053 0.12814023 0.30470927 0.07850695]
 [0.02494697 0.9886128  0.57743703 0.60855996 0.31340938 0.95845625
  0.54852424 0.2079923  0.83778704 0.97841092]
 [0.29734673 0.42115319 0.41768321 0.97089129 0.19022215 0.82975459
  0.93684472 0.87964089 0.12783016 0.24835052]
 [0.77438805 0.25057956 0.07891545 0.85377937 0.24578527 0.14018645
  0.64462146 0.77550531 0.29319536 0.34078683]
 [0.30938916 0.19699374 0.473414   0.82546128 0.95568937 0.24793517
  0.9774568  0.12120288 0.16797512 0.55128185]
 [0.35881294 0.74165176 0.85645288 0.81360007 0.68102714 0.88965358
  0.34913089 0.0496484  0.50618886 0.47266089]
 [0.95246962 0.1154953  0.59606097 0.1936773  0.30257594 0.33925187
  0.35254554 0.22750955 0.48674354 0.82855152]
 [0.66209791 0.90679824 0.27004347 0.43997927 0.53716644 0.88528726
  0.53760389 0.40234828 0.5978898  0.84178374]
 [0.17143477 0.6821269  0.26435876 0.62378164 0.04110644 0.53049138
  0.74357803

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [66]:
array = np.random.random(30)
mean_value = np.mean(array)
print(array)
print("mean_value =", mean_value)

[0.47294573 0.51962798 0.87000274 0.19362443 0.88862033 0.84055055
 0.94565252 0.93277312 0.44352246 0.62696095 0.93202617 0.48951874
 0.48327814 0.36133255 0.55532749 0.29180371 0.47867284 0.96040121
 0.08926933 0.66318449 0.75444375 0.26864219 0.39548039 0.77946031
 0.46303878 0.01992977 0.47948401 0.27779995 0.65840489 0.9297305 ]
mean_value = 0.5688503339786112


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [68]:
array2d = np.zeros((5,5))

array2d[0, :] = 1
array2d[-1, :] = 1
array2d[:, 0] = 1
array2d[:, -1] = 1

print(array2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [72]:
matrix = np.diag([1,2,3,4], k= -1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [74]:
matrix = np.zeros((8,8))
matrix[1::2, ::2] = 1 #홀수행의 짝수열에 1배치
matrix[::2, 1::2] = 1 #짝수행의 홀수열에 1배치
print(matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [76]:
array = np.unravel_index(100, (6,7,8))
print(array)

(1, 5, 4)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [84]:
array = np.random.random((5,5))
mean_value = np.mean(array)
std_value = np.std(array)
norm_array = (array - mean_value) / std_value
print(norm_array)

[[-1.89773733  1.41927535 -0.20286329 -1.66433156  0.99714578]
 [-0.05097949  0.50941371 -0.45834858  0.26789047 -0.84219415]
 [ 0.19747574  1.42070005 -1.26900342 -0.95206816  0.14956016]
 [ 0.41373127  1.75167967 -0.27314962  0.64154715  1.43783555]
 [ 0.78865297 -1.39657678 -0.77738901  0.50192534 -0.71219179]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [99]:
rgba = np.dtype([('Red', np.ubyte), ('Green', np.ubyte), ('Blue', np.ubyte), ('Alpha', np.ubyte)]) #alpha 투명도
print(rgba)

[('Red', 'u1'), ('Green', 'u1'), ('Blue', 'u1'), ('Alpha', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [1]:
# column 3

In [2]:
# column 2


In [3]:
# column 3
