#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [12]:
import numpy as np

A = np.random.random((5,3))
B = np.random.random((3,2))

print("5X3 matrix:\n", A)
print("3X2 matrix:\n", B)
print("Multiply two matrix:\n", np.dot(A,B))

5X3 matrix:
 [[0.53276213 0.53601047 0.96739377]
 [0.41959824 0.61345729 0.57908554]
 [0.00902509 0.65667978 0.84104025]
 [0.38888531 0.18722012 0.37284975]
 [0.25759131 0.07173383 0.64735974]]
3X2 matrix:
 [[0.41861342 0.8562755 ]
 [0.44726529 0.27296544]
 [0.54210435 0.32640928]]
Multiply two matrix:
 [[0.98718863 0.91826979]
 [0.7639524  0.71576322]
 [0.75341968 0.46150219]
 [0.44865315 0.5057992 ]
 [0.49085176 0.45145421]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [41]:
array1 = np.arange(10)
array1[(3 < array1) & (array1 < 8)] *= -1
print(array1)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9 10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

1. 유효
2. 유효
3. 무효: '<-'는 존재하지 않는 연산자
4. 유효
5. 유효
6. 무효: 잘못된 비교 연산 

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [17]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

# 1. 0 / 0 은 수학적으로 정의되지 않음. 
# 2. 0 // 0 정수 나눗셈 역시 정의되지 않음
# 이때, '/'와 '//'의 차이점은 '/'은 실수형 나눗셈, '//'은 나눈 후 내림 결과 도출
# NaN을 값을 포함한 배열 생성 -> 정수형으로 변환 -> 실수형으로 변환

/var/folders/t6/l14298n92xx0dtft2b1m3sqm0000gn/T/ipykernel_51406/3176601847.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/var/folders/t6/l14298n92xx0dtft2b1m3sqm0000gn/T/ipykernel_51406/3176601847.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/var/folders/t6/l14298n92xx0dtft2b1m3sqm0000gn/T/ipykernel_51406/3176601847.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([0.])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [43]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)

common_values = np.intersect1d(Z1, Z2)
print(common_values)

[2 2 8 3 6 4 4 1 3 1]
[6 4 3 6 1 6 8 8 3 0]
[1 3 4 6 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


False, emath가 복소수

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [39]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')

print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [27]:
A = np.random.rand(3, 3) #3X3 랜덤 배열 생성
B = np.random.rand(3, 3)

C = np.add(A, B)

D = np.divide(A, -2)

E = np.multiply(A, A)

print(E)

[[0.49323469 0.35407964 0.18991094]
 [0.06770268 0.25235478 0.26416625]
 [0.47730293 0.19946589 0.91656663]]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [45]:
array2 = np.random.uniform(0, 10, 10)

# 방법 1: np.floor() 사용
int_part1 = np.floor(array2).astype(int)

# 방법 2: astype를 사용
int_part2 = array2.astype(int)

print("원본 배열:", array2)
print("방법 1:", int_part1)
print("방법 2:", int_part2)

원본 배열: [5.9416643  1.59039577 0.48620343 2.39899472 7.20518049 0.24541514
 4.92855808 8.31660573 4.48379652 8.31124722]
방법 1: [5 1 0 2 7 0 4 8 4 8]
방법 2: [5 1 0 2 7 0 4 8 4 8]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

[[1 0 1 4 4]
 [3 0 3 0 0]
 [1 4 4 3 0]
 [4 3 4 2 3]
 [1 3 2 3 3]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [47]:
vector = np.random.rand(10)

sorted_vector = np.sort(vector)

print("Original Vector:\n", vector)
print("Sorted Vector:\n", sorted_vector)

Original Vector:
 [0.22423375 0.1669539  0.79945778 0.84275508 0.89484515 0.47981317
 0.66246631 0.18687501 0.25171494 0.30868235]
Sorted Vector:
 [0.1669539  0.18687501 0.22423375 0.25171494 0.30868235 0.47981317
 0.66246631 0.79945778 0.84275508 0.89484515]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [29]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(np.array_equal(A,B))

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [49]:
# 랜덤 행렬 생성
cartesian_matrix = np.random.rand(10, 2)

# 극좌표 변환
r = np.sqrt(cartesian_matrix[:, 0]**2 + cartesian_matrix[:, 1]**2)
theta = np.arctan2(cartesian_matrix[:, 1], cartesian_matrix[:, 0])

# 결과 출력
print("Cartesian Coordinates:", cartesian_matrix)
print("\nPolar Coordinates:", np.column_stack((r, theta)))

Cartesian Coordinates: [[0.16455326 0.83612806]
 [0.7723868  0.22242292]
 [0.91675506 0.11645851]
 [0.99530128 0.42786906]
 [0.33281389 0.42264258]
 [0.65925434 0.29539697]
 [0.72729431 0.66547241]
 [0.58265215 0.66496491]
 [0.70227414 0.37574459]
 [0.64129187 0.78441543]]

Polar Coordinates: [[0.8521666  1.37647582]
 [0.80377442 0.28038233]
 [0.92412252 0.1263566 ]
 [1.08337277 0.40600436]
 [0.53795152 0.90374898]
 [0.72240962 0.42125395]
 [0.98580452 0.74103944]
 [0.88411643 0.85127867]
 [0.79647534 0.49128492]
 [1.01319437 0.88545072]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [58]:
Z = np.random.random(10)
maximum_index = Z.argmax()
Z[maximum_index]=0
Z

array([0.62751788, 0.07920186, 0.04659833, 0.44967325, 0.22038295,
       0.11091666, 0.58064973, 0.48131174, 0.        , 0.75715238])

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [53]:
Z = np.array([0.44543135, 0.15272685, 0.        , 0.87774566, 0.23038287,
       0.63059028, 0.85004996, 0.4217004 , 0.87033034, 0.32653317]) 

v = np.random.uniform(0, 100)  

dist = np.abs(Z - v)

index = np.argmin(dist)

closest_value = Z[index]

print("Closest value in a vector Z:", closest_value)

Closest value in a vector Z: 0.87774566


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [35]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z): # enumerate() - (인덱스,값)을 동시에 반환하는 함수 / index() - 인덱스만 반환하는 함수

    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [51]:
n = 3
p = 2
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),8)
print(Z)

[[8. 0. 0.]
 [8. 0. 0.]
 [0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [60]:
array39_1 = np.array([[1, 7, 3],
                     [9, 0, 1],
                     [8, 6, 4]])
indices = [0,2,1]
answer39_1 = array39_1[indices]
print(array39_1,'\n\n',answer39_1)

[[1 7 3]
 [9 0 1]
 [8 6 4]] 

 [[1 7 3]
 [8 6 4]
 [9 0 1]]


In [62]:
array39_2 = np.array([[7, 6, 7],
                    [7, 8, 4],
                    [5, 4, 7]])
indices = [2,0,1]
answer39_2 = array39_2[indices]
print(array39_2,'\n\n',answer39_2)

[[7 6 7]
 [7 8 4]
 [5 4 7]] 

 [[5 4 7]
 [7 6 7]
 [7 8 4]]


In [64]:
array39_3 = np.array([[7, 9, 5],
                      [1, 8, 2],
                      [6, 8, 1]])
indices = [2,1,0]
answer39_3 = array39_3[indices]
print(array39_3,'\n\n',answer39_3)

[[7 9 5]
 [1 8 2]
 [6 8 1]] 

 [[6 8 1]
 [1 8 2]
 [7 9 5]]
